# Fastpitch Curator Context Samples

[samples.tech-news-selection]
score = 3

[[samples.tech-news-selection.messages]]
role = "user"
content = """
{{{stories}}}
"""

[[samples.tech-news-selection.messages]]
role = "assistant"
content = """
Based on the provided articles, I'll select the 5 most impactful stories for software engineers.
"""