name: Deploy Infrastructure (Hetzner)

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths: ["infra/terraform/hetzner/**"]

# Prevent concurrent Terraform operations
concurrency:
  group: terraform-state
  cancel-in-progress: false

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: infrastructure
    defaults:
      run:
        working-directory: infra/terraform/hetzner

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: DeterminateSystems/nix-installer-action@main
        with: { determinate: true }

      # - uses: DeterminateSystems/flakehub-cache-action@main  # Disabled FlakeHub caching

      - name: Setup Terraform Environment
        uses: ./.github/actions/setup-terraform-env
        with:
          op-service-account-token: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init -backend-config="endpoint=${{ env.TERRAFORM_S3_ENDPOINT }}"

      - name: Terraform Plan
        run: |
          terraform plan \
            -var="github_username=${{ github.repository_owner }}"

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: |
          terraform apply -auto-approve \
            -var="github_username=${{ github.repository_owner }}"

