name: Retry Kamal Deploy

on:
  workflow_dispatch:
    inputs:
      unlock_first:
        description: 'Unlock any existing deployment locks before retrying'
        required: false
        type: boolean
        default: true
      server_ip:
        description: 'Server IP address (leave empty to auto-detect from Terraform)'
        required: false
        type: string

jobs:
  unlock:
    name: Unlock Existing Deploy
    if: inputs.unlock_first == true
    uses: ./.github/workflows/kamal-unlock.yml
    with:
      server_ip: ${{ inputs.server_ip }}
    secrets: inherit

  deploy:
    name: Retry Deployment
    needs: [unlock]
    if: always() && (needs.unlock.result == 'success' || needs.unlock.result == 'skipped')
    uses: ./.github/workflows/deploy-boltfoundry-com.yml
    secrets: inherit

  summary:
    name: Deployment Summary
    runs-on: ubuntu-latest
    needs: [deploy]
    if: always()
    
    steps:
      - name: Generate Summary
        run: |
          echo "## Kamal Deploy Retry Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          
          if [ "${{ inputs.unlock_first }}" == "true" ]; then
            echo "- **Pre-deployment unlock**: Enabled ✅" >> $GITHUB_STEP_SUMMARY
          else
            echo "- **Pre-deployment unlock**: Skipped ⏭️" >> $GITHUB_STEP_SUMMARY
          fi
          
          if [ "${{ needs.deploy.result }}" == "success" ]; then
            echo "- **Deployment Status**: Success ✅" >> $GITHUB_STEP_SUMMARY
          elif [ "${{ needs.deploy.result }}" == "failure" ]; then
            echo "- **Deployment Status**: Failed ❌" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "### Troubleshooting Steps" >> $GITHUB_STEP_SUMMARY
            echo "1. Check the deploy job logs for specific errors" >> $GITHUB_STEP_SUMMARY
            echo "2. If lock error persists, run 'Unlock Kamal Deploy' workflow with force=true" >> $GITHUB_STEP_SUMMARY
            echo "3. SSH into the server and check Kamal logs: \`kamal app logs\`" >> $GITHUB_STEP_SUMMARY
          else
            echo "- **Deployment Status**: ${{ needs.deploy.result }} ⚠️" >> $GITHUB_STEP_SUMMARY
          fi