name: Notify internalbf of changes

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      target_branch:
        description: "Target branch in internalbf repo"
        required: false
        default: "main"
        type: string

jobs:
  notify-internalbf:
    name: Trigger internalbf submodule update
    runs-on: ubuntu-latest
    environment: ci
    env:
      OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@main
        with: { determinate: true }

      # - uses: DeterminateSystems/flakehub-cache-action@main  # Disabled FlakeHub caching

      - name: Load secrets and trigger workflow
        run: |
          nix develop .#github-actions --accept-flake-config --command bash -euc "
            export PATH=\"\$PATH:\$PWD/infra/bin\"
            export OP_SERVICE_ACCOUNT_TOKEN=\"$OP_SERVICE_ACCOUNT_TOKEN\"

            # Load secrets from 1Password
            bft sitevar sync --force

            # Source the secrets file to get CODEBOT_GITHUB_PAT
            source .env.secrets

            # Determine target branch
            TARGET_BRANCH=\"${{ github.event.inputs.target_branch || 'main' }}\"

            # Trigger the internalbf workflow
            curl -X POST \
              -H \"Accept: application/vnd.github+json\" \
              -H \"Authorization: Bearer \$CODEBOT_GITHUB_PAT\" \
              -H \"X-GitHub-Api-Version: 2022-11-28\" \
              https://api.github.com/repos/bolt-foundry/internalbf/dispatches \
              -d \"{\\\"event_type\\\":\\\"update-bfmono-submodule\\\",\\\"client_payload\\\":{\\\"target_branch\\\":\\\"\$TARGET_BRANCH\\\"}}\"
          "
